{% set version = "0.1.0" %}

package:
  name: simple_adder
  version: "{{ version }}"

# source:
#   git_url: https://github.com/openai/openai-python
#   git_rev: v{{ version }}

source:
  path: /home/ubuntu/chaquopy/workdir/pybind_test

requirements:
  host:
    - python

about:
  license_file: LICENSE
