{% set version = "1.93.0" %}

package:
  name: openai
  version: "{{ version }}"

source:
  git_url: https://github.com/openai/openai-python
  git_rev: v{{ version }}

# source:
#   path: /home/ubuntu/chaquopy/workdir/openai-python

requirements:
  host:
    - python

about:
  license_file: LICENSE
