package:
  name: numpy
  version: "1.26.2"

build:
  number: 0
  script_env:
    - SETUPTOOLS_USE_DISTUTILS=local

source:
  path: /home/ubuntu/chaquopy/workdir/numpy

requirements:
  build:
    # NumPy doesn't officially support building with setuptools on Python 3.12, but it
    # still works with this version, plus a couple of patches.
    - setuptools 69.0.2
  host:
    - chaquopy-openblas 0.2.20
