{% set version = "0.1.0" %}

package:
  name: edgevecdb
  version: "{{ version }}"

source:
  git_url: https://github.com/hxlou/LightFaiss.git
  git_rev: chaquopy-TEMP

requirements:
  host:
    - python
    - chaquopy-libomp 18

about:
  license_file: LICENSE
