{% set version = "0.1.0" %}

package:
  name: edgevecdb
  version: "{{ version }}"

# source:
#   git_url: https://github.com/openai/openai-python
#   git_rev: v{{ version }}

source:
  path: /home/ubuntu/chaquopy/workdir/LightFaiss

requirements:
  host:
    - python
    - chaquopy-libomp 18

about:
  license_file: LICENSE
