# Updates to this package should be backward-compatible, but it doesn't always work that
# way, so make sure to test new versions with existing packages
# (https://github.com/chaquo/chaquopy/issues/1171#issuecomment-2402757412).

package:
  name: chaquopy-libomp
  version: "18"  # See version.sh.

source: null
